name: âš¡ Integration checks

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  lint:
    name: â¬£ lint / format
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4

      - name: ðŸ“¦ Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: âŽ” Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
          cache-dependency-path: ./package.json

      - name: ðŸ“¥ Install deps
        run: pnpm install --frozen-lockfile

      - name: ðŸ““ Format
        run: pnpm format-ci

      - name: ðŸ”¬ Lint
        run: pnpm lint

  typecheck:
    name: Ê¦ TypeScript
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4

      - name: ðŸ“¦ Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: âŽ” Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
          cache-dependency-path: ./package.json

      - name: ðŸ“¥ Install deps
        run: pnpm install --frozen-lockfile

      - name: ðŸ”Ž Type check
        run: pnpm type-check

  tests:
    name: ðŸŽ¯ Tests
    runs-on: ubuntu-latest
    steps:
      - name: â¬‡ï¸ Checkout repo
        uses: actions/checkout@v4

      - name: ðŸ“¦ Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: latest

      - name: âŽ” Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
          cache-dependency-path: ./package.json

      - name: ðŸ“¥ Install deps
        run: pnpm install --frozen-lockfile

      - name: ðŸŽ­ Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: â›› Waiting for Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: waitForVercelPreview
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 240

      - name: âš™ï¸ Set tests related env variables
        run: |
          echo "PLAYWRIGHT=true" >> $GITHUB_ENV
          echo "PLAYWRIGHT_WEBSITE_URL=${{steps.waitForVercelPreview.outputs.url}}" >> $GITHUB_ENV

      - name: ðŸŽ­ Run Playwright tests
        run: pnpm exec playwright test

      - name: ðŸ’¾ Uploading playwright artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
